defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.eval.eval_diffusion_agent.EvalDiffusionAgent

name: ${env_name}_eval_diffusion_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/robomimic-eval/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: /home/yl/dppo/log/robomimic-pretrain/square_pre_diffusion_unet_ta8_td20/2024-09-24_22-12-27_42/checkpoint/state_5500.pt
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}.json
normalization_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env_name}-ph/normalization.npz

seed: 42
device: cuda:0
env_name: square
obs_dim: 23
action_dim: 7
transition_dim: ${action_dim}
denoising_steps: 20
cond_steps: 2
horizon_steps: 8
act_steps: 8

n_steps: 300  # each episode takes max_episode_steps / act_steps steps
render_num: 20

env:
  n_envs: 20
  name: ${env_name}
  best_reward_threshold_for_success: 1
  max_episode_steps: 300
  wrappers:
    robomimic_lowdim:
      normalization_path: ${normalization_path}
      low_dim_keys: ['robot0_eef_pos',
                    'robot0_eef_quat',
                    'robot0_gripper_qpos',
                    'object'] # same order of preprocessed observations
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

model:
  _target_: model.diffusion.diffusion.DiffusionModel
  predict_epsilon: True
  denoised_clip_value: 1.0
  randn_clip_value: 3
  #
  network_path: ${base_policy_path}
  network:
    _target_: model.diffusion.unet.Unet1D
    diffusion_step_embed_dim: 16
    dim: 64
    dim_mults: [1, 2]
    kernel_size: 5
    n_groups: 8
    smaller_encoder: False
    cond_predict_scale: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    transition_dim: ${transition_dim}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}