defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.critic.train_critic.PreTrainCritic

name: ${env_name}_pre_critic
logdir: ${oc.env:DPPO_LOG_DIR}/robomimic-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env_name}-ph/train.npz
normalization_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env_name}-ph/normalization.npz
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}.json

seed: 42
device: cuda:0
env_name: square
obs_dim: 23
action_dim: 7
transition_dim: ${action_dim}
denoising_steps: 20
horizon_steps: 8
act_steps: 8
cond_steps: 2
n_steps: 300
render_num: 0

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: robomimic-${env_name}-critic
  run: ${now:%H-%M-%S}_${name}

train:
  n_epochs: 1000
  batch_size: 35000
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 10000
    warmup_steps: 100
    min_lr: 1e-5
  epoch_start_ema: 20
  update_ema_freq: 10
  save_model_freq: 20

  reward_scale_const: 1.0
  gae_lambda: 0.95
  gamma: 0.999
  reward_scale_running: False

model:
  _target_: model.common.critic.CriticObs
  cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
  mlp_dims: [256, 256, 256]
  activation_type: Mish
  residual_style: True

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.CriticDataset
  dataset_path: ${train_dataset_path}
  cond_steps: ${cond_steps}
  act_steps: ${act_steps}
  device: ${device}